#!/usr/bin/env bash

niri msg -j windows | \
    jq -rc 'sort_by(.is_focused | not)[] | [.id, "\(.app_id) - \(.title)"] | @tsv' | \
    fuzzel --prompt "Focus window: " -d --with-nth=2 --accept-nth=1 | \
    xargs niri msg action focus-window --id
