#!/usr/bin/env bash

niri msg -j windows | \
    jq -rc '.[] | [.id, "\(.app_id) - \(.title)"] | @tsv' | \
    fuzzel -w 80 -d --with-nth=2 --accept-nth=1 | \
    xargs niri msg action focus-window --id
