#!/usr/bin/env bash
# find who is listening on port
# USAGE: portlocate 8888

set -euo pipefail

port=$1
# print the header and rows matching the port
sudo lsof -PiTCP | awk "NR == 1 || /:$port(->| \(LISTEN\))/"
