#!/usr/bin/env bash
# pull all repos open in any tmux pane

# ensures one pull per repo

tmux list-panes -a -F "#{pane_current_path}" |  
while read -r dir ; do
    cd "$dir" || continue 
    if git rev-parse --is-inside-work-tree > /dev/null 2>&1; then
        git rev-parse --show-toplevel
    fi
done | sort -n | uniq | parallel 'cd {} && pwd && git pull --autostash'
