#!/usr/bin/env bash

set -u

title=$1

if [ -n "${TMUX_PANE:-}" ] &&
   window_id=$(tmux display-message -p -t "$TMUX_PANE" -F '#{window_id}' 2>/dev/null) &&
   [ -n "$window_id" ]; then
  tmux rename-window -t "$window_id" "$title" || true
fi
