#!/usr/bin/env bash
# pull all repos open in any tmux pane

# ensures one pull per repo

tmux list-panes -a -F "#{pane_current_path}" |  
while read -r dir ; do
    cd $dir && git rev-parse --show-toplevel
done | sort -n | uniq | parallel 'cd {} && pwd && git pull --autostash'
