#!/usr/bin/env bash

tmux list-panes -a -F "#{session_name}:#{window_index}.#{pane_index} #{pane_pid}" |
while read -r pane pid; do
    child_pid=$(pgrep -P $pid)
    # if the pane has no child command running
    if [[ -z $child_pid ]]; then
        tmux respawn-pane -t $pane -k
    fi
done

tmux respawn-pane -k
