#!/usr/bin/env bash

set -euo pipefail

tailscale status --json | jq -r '.Peer.[].HostName | select(. != "localhost")' | \
    fuzzel --prompt "Open new ssh window: " -d | \
    xargs -I{} wezterm ssh --class {} {}
