# Config options https://starship.rs/config/

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

[git_metrics]
disabled = false

[status]
disabled = false

[sudo]
disabled = false

[direnv]
disabled = false
allowed_msg = "✓"
format = "[$symbol$allowed$loaded]($style) "
denied_msg = "x"
loaded_msg = "󰡴"
not_allowed_msg = "x"
unloaded_msg = "󱦟"
